### ISSUE TITLE
undefined symbol: nvds_msg2p_generate_multiple_new

### ISSUE THREAD

**Issue by MIMNSI** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#39]
I'm getting the following error when running with [sink1] enabled. 
Hardware: Jetson AGX Xavier
Deepstream 6.0

(deepstream-test5-analytics:19188): GStreamer-WARNING **: 04:54:59.302: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_msgconv.so': /usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_msgconv.so: undefined symbol: nvds_msg2p_generate_multiple_new
** ERROR: <create_msg_conv_broker_bin:234>: Failed to create 'sink_sub_bin_transform2'
** ERROR: <create_msg_conv_broker_bin:278>: create_msg_conv_broker_bin failed
** ERROR: <create_sink_bin:781>: create_sink_bin failed
** ERROR: <create_processing_instance:815>: create_processing_instance failed
** ERROR: <create_pipeline:1323>: create_pipeline failed
** ERROR: <main:1041>: Failed to create pipeline
Quitting
App run failed

I did replace the system libnvdsgst_msgconv.so with the one provided in your repo.
Is this a dependency issue caused by DS 6.0?

**Comment by monjha** [comment]
Hi Mimnsi,

Thank you for reporting the issue. I will update the repo for ds 6.0.

**Comment by monjha** [comment]
Hello,

Added the support for ds6.0. Please check ds_6.0 branch.

**Comment by sijumanuel** [comment]
Sorry I ddint get.Do you mean install Deepstream 6.0 again or there is some specific link

**Comment by MIMNSI** [comment]
> Hello,
> 
> Added the support for ds6.0. Please check ds_6.0 branch.

Awesome, Thank you so much!

**Comment by MIMNSI** [comment]
> Sorry I ddint get.Do you mean install Deepstream 6.0 again or there is some specific link

I have DS 6 on my system and the repo was built for 5.0 so there were dependency issues earlier. They updated the repo to support DS 6 so it should work now. We have to use the other branch now instead of the master.

**Comment by vertcli** [comment]
I have tried it inside deepstream-l4t tag 6.1-triton and I still have this issue using branch ds_6.0
